# 文件路径: dbt_transform/profiles.yml

dbt_transform:
  target: dev
  outputs:
    dev:
      type: databricks
      catalog: nyc
      host: https://dbc-f9d1ed70-8f10.cloud.databricks.com
      http_path: /sql/1.0/warehouses/e6851c934b9e0136
      schema: dev 
      auth_type: oauth
      profile: DEFAULT
      threads: 4

      