# 文件路径: dbt_transform/profiles.yml

dbt_transform:
  target: dev
  outputs:
    dev:
      type: databricks
      catalog: nyc
      host: https://dbc-f9d1ed70-8f10.cloud.databricks.com
      http_path: /sql/1.0/warehouses/e6851c934b9e0136
      schema: dev 
      auth_type: oauth
      profile: DEFAULT
      threads: 4


    ci:
      type: databricks
      catalog: dummy_catalog
      schema: dummy_schema
      # 强制指向本地回环，切断向云端发起 TCP 连接的可能，实现真正的 Fail-Fast
      host: "127.0.0.1" 
      http_path: "/dummy"
      token: "dummy_token"
      connect_retries: 0 # 禁用重试，避免静默等待
      